### ISSUE TITLE
Discrete-Action Space Support

### ISSUE THREAD

**Issue by rohanpaleja27** [voot-t/vild_code#2]
Hi,

This is a great repository! I was wondering if discrete action-spaces are supported or not. I see some TODOs within the codebase regarding that.

Thanks,

**Comment by voot-t** [comment]
Hi,

Sorry for my late reply.
Discrete action spaces are not supported. 
We did not continue this work since we found another approach which does not require a parametric noise model and therefore is applicable to both discrete and continuous action spaces. 
If you are interested in it please see our [paper](https://proceedings.mlr.press/v130/tangkaratt21a) and [repo](https://github.com/voot-t/ril_co).
